### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Qwash** [Reeywhaar/tabsaver#1]
Can u make a default name value for new entries "current date & time"
Can u make it more like firefox session restore feature
1- Save & restore Cookies
2- Restore text values
Can u add a button to "Save current session and exit" [>>restore next launch]
I'm looking for an alternative to
https://addons.mozilla.org/en-US/firefox/addon/save-session
I hope if u can add it's feature to ur addon or make a new simple addon with just "Save current session & Exit" button

**Comment by reeywhaar** [comment]
Dear Qwash,

Cookies and tab state management are not domain of responsibility of this extension. I'm trying to keep this extension simple and to the point of saving and restoring window tabs.
It would be great, if there was tab state API, so I could easily restore tab snapshot, but now it's a way full of quirks and obstacles. I need to think about it, thank you! :-)

As for cookies, I will try to integrate extension with [Containers](https://testpilot.firefox.com/experiments/containers/), once they will be stabilized.

As for "Save current session and exit" I think it better to set the option `when firefox starts` in the preferences to `show your windows and tabs from last time`, because it's a standard feature. But, it's just suggestion, I don't know your use case, actually. More to this solution, is that current WebExtension API doesn't provide methods to quit or reload browser, so now it's just impossible to recreate "Save current session and exit" extension via WebExtension.

Thank you for your suggestions 👍
