### ISSUE TITLE
Import TabSets not click-able

### ISSUE THREAD

**Issue by robertberrier** [Reeywhaar/tabsaver#11]
When going into the objects of this plugin, to import a previously saved TabSet,
The button 'Import TabSets' does nothing. The graphic is there, but there is no interation with it what so ever. As if it is simply an image.

Export TabSets works fine
Clear TabSets works fine

Adjusting window/browser size has no effect.

V0.1.1 of this pluging

**Comment by reeywhaar** [comment]
Oh, look, you right! Seems like I broke something between updates.

**Comment by reeywhaar** [comment]
Fixed in a23c9782c984f9eda67fc7b0e85dca7f5581ecf0
Version available in AMO
Thanks for report!

For the history:
Previous version had the flow like that:
* user clicks "Import"
* import handler calls store handler, which calls `browser.runtime.sendMessage("import")`
* browser event listener catches message and start processing by creating `file` input, appending to background page DOM, attaches `changes` event listener and calls `input.click()`.
  That where the problem was. Dev environment somehow allowed `input.click()`, while if addon installed not via `web-ext` such behaviour is denied, since `input.click()` wasn't called as a result of user action, because the user action chain was lost when action was passed via `browser.runtime()` [Reference](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/User_actions)

Current flow:
* user clicks "import"
* click handler does all logic of creating, listening, appending `file` input, so we don't loose user action handler status, and then sends received data via `browser.runtime.send({type: "import", data})`

P.S. Strange that I am myself found this issue on v.0.1.3, and previous versions seemed to work fine, I remember someone wrote the review regarding issue on AMO, and I did immediately check and everything was fine. Maybe some changes of FF version caused the isuue.
